version: 0.2

env:
  variables:
    AWS_REGION: "us-west-2"
    REACT_APP_API_SERVICE_URL: "http://localhost:4005"
  parameter-store:
    ACCESS_KEY_ID: /CodeBuild/ACCESS_KEY_ID
    SECRET_ACCESS_KEY: /CodeBuild/SECRET_ACCESS_KEY
    AWS_BUCKET: /CodeBuild/AWS_BUCKET
    GOOGLE_GEOCODING_API_KEY: /CodeBuild/GOOGLE_GEOCODING_API_KEY
    AWS_ACCOUNT_ID: /CodeBuild/AWS_ACCOUNT_ID

phases:
  pre_build:
    commands:
      - echo logging in to ecr...
      - >
        aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo building images...
      - >
        docker build \                       
          -f server/Dockerfile.prod \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/skatespot-server:prod \
          ./server
      - >
        docker build \
          -f client/Dockerfile.prod \
          -t $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/skatespot-client:prod \
          ./client
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/skatespot-server:prod
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/skatespot-client:prod
