version: 0.2

env:
  variables:
    AWS_REGION: "us-west-2"
    REACT_APP_API_SERVICE_URL: "http://SkateSpot-alb-14445569.us-west-2.elb.amazonaws.com"
  parameter-store:
    ACCESS_KEY_ID: /CodeBuild/ACCESS_KEY_ID
    SECRET_ACCESS_KEY: /CodeBuild/SECRET_ACCESS_KEY
    AWS_BUCKET: /CodeBuild/AWS_BUCKET
    GOOGLE_GEOCODING_API_KEY: /CodeBuild/GOOGLE_GEOCODING_API_KEY
    AWS_ACCOUNT_ID: /CodeBuild/AWS_ACCOUNT_ID
    DATABASE_HOST: /CodeBuild/DATABASE_HOST
    DATABASE_PASSWORD: /CodeBuild/DATABASE_PASSWORD
    DATABASE_USERNAME: /CodeBuild/DATABASE_USERNAME

phases:
  pre_build:
    commands:
      - echo logging in to ecr...
      - >
        aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - >
        docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/skatespot-server:prod || true
      - >
        docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/skatespot-client:prod || true
  build:
    commands:
      - echo building images...
      - >
        docker build -f ./server/Dockerfile.prod ./server \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/skatespot-server:prod \
          --build-arg NODE_ENV=production \
          --build-arg ACCESS_KEY_ID=$ACCESS_KEY_ID \
          --build-arg SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY \
          --build-arg REGION=$AWS_REGION \
          --build-arg AWS_BUCKET=$AWS_BUCKET \
          --build-arg GOOGLE_GEOCODING_API_KEY=$GOOGLE_GEOCODING_API_KEY \
          --build-arg DATABASE_USERNAME=$DATABASE_USERNAME \
          --build-arg DATABASE_PASSWORD=$DATABASE_PASSWORD \
          --build-arg DATABASE_HOST=$DATABASE_HOST
      - >
        docker build -f ./client/Dockerfile.prod ./client \
          -t $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/skatespot-client:prod \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_API_SERVICE_URL=$REACT_APP_API_SERVICE_URL \
          --build-arg REACT_APP_GOOGLE_MAPS_API_KEY=$REACT_APP_GOOGLE_MAPS_API_KEY
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/skatespot-server:prod
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/skatespot-client:prod
